package com.example.poc.entity;

import jakarta.persistence.*;
import java.time.Instant;

@Entity
@Table(name = "crew_login")
public class CrewLogin {

    /** GUID generated by the browser page that registered this session. */
    @Id
    @Column(name = "id", length = 36, nullable = false)
    private String id;

    @Column(name = "crew_id", nullable = false, length = 32)
    private String crewId;

    @Column(name = "logged_in_at", nullable = false)
    private Instant loggedInAt = Instant.now();

    @Column(name = "logged_out_at")
    private Instant loggedOutAt;

    public CrewLogin() {}

    public CrewLogin(String id, String crewId) {
        this.id = id;
        this.crewId = crewId;
        this.loggedInAt = Instant.now();
    }

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }
    public String getCrewId() { return crewId; }
    public void setCrewId(String crewId) { this.crewId = crewId; }
    public Instant getLoggedInAt() { return loggedInAt; }
    public void setLoggedInAt(Instant loggedInAt) { this.loggedInAt = loggedInAt; }
    public Instant getLoggedOutAt() { return loggedOutAt; }
    public void setLoggedOutAt(Instant loggedOutAt) { this.loggedOutAt = loggedOutAt; }
}
